routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('products', 'ProductController');
        Route::get('imageDelete/{id}', 'ProductController@imageDelete')->name('products.imageDelete');
        Route::get('varientDelete/{id}', 'ProductController@varientDelete')->name('products.varientDelete');

    });
    
    Route::get('view-products', 'ProductController@index')->name('userProduct.index');
    Route::get('product-detail/{id}', 'ProductController@getProduct')->name('userProduct.detail');

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function images(){

        return $this->hasMany(ProductImage::class);
    
    }

    public function varients(){

        return $this->hasMany(ProductVarient::class);
    
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductVarient;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {
        
        $data = Product::with('images','varients')->latest()->paginate(10);
        return view('admin.product.index',compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create(Request $request)
    {
        return view('admin.product.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required',
            'actual_price' => 'required',
            'sell_price' => 'required'
        ]);

        // return $request->all();

        $data = $request->except(['_token', '_method','image','varient']);
       
        $product = Product::create($data);
        
            foreach($request->image as $proImage){
                    
                $proImageData['product_id'] =  $product->id;                
                $proImageData['image'] = $this->fileUpload($proImage, 'product')['name'] ?? null;


                ProductImage::create($proImageData);

            } 
            
            foreach($request->varient as $val){
                    
                $proData['product_id'] =  $product->id;
                $proData['name'] =  $val['name'];
                $proData['value'] =  $val['value'];
                
                ProductVarient::create($proData);

            }
  
        notify()->success('Product Added Successfully');
        return redirect()->route('products.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Product::with('images','varients')->find(base64_decode($id));
        // return $data;
        return view('admin.product.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name'    => 'required',
            'actual_price' => 'required',
            'sell_price' => 'required'
        ]);

        $data = $request->except(['_token', '_method','image','varient']);

        $product = Product::find($id);
        $product->update = $data;
        
        foreach($request->image as $proImage){
                
            $proImageData['product_id'] =  $product->id;
            $proImageData['image'] = $this->fileUpload($proImage, 'product')['name'] ?? null;

            ProductImage::create($proImageData);

        } 
            
        foreach($request->varient as $val){
                
            $proData['product_id'] =  $product->id;
            $proData['name'] =  $val['name'];
            $proData['value'] =  $val['value'];
            
            if($val['id']>0){
                ProductVarient::updateOrCreate(
                    [
                         'id'=> $val['id']
                    ],
                $proData
                );
            }
            else{
                ProductVarient::create($proData);
            }
        }

        notify()->success('Product successfuly updated');
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Product::destroy(base64_decode($id));        
        ProductImage::where('product_id',base64_decode($id))->delete();
        ProductVarient::where('product_id',base64_decode($id))->delete();

        notify()->success('Product deleted successfully');
        return back();
        
    }

    public function imageDelete($id){

        ProductImage::destroy($id);
        notify()->success('Product image deleted successfully');
        return redirect()->back();

    }
    
    public function varientDelete($id){

        ProductVarient::destroy($id);
        notify()->success('Product varient deleted successfully');
        return redirect()->back();

    }


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;

class ProductController extends Controller
{
    public function index(){

        $data = Product::with('images','varients')->latest()->paginate(5);
        // return $data;
        return view('product.index',compact('data'));
    
    }

    public function getProduct($id){

        $data = Product::with('images','varients')->find(base64_decode($id));
        // return $data;
        return view('product.detail',compact('data'));

    }
}

resources/views/admin/product/add.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Add Prodcut</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('products.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" enctype="multipart/form-data" action="{{route('products.store')}}">
            @csrf
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Name:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Name" value="{{old('name')}}" name="name">
            </div>   
            @error('name')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Sale Price:</label>
                <input type="number" min="1" step="any" max="10000" class="form-control" required id="" placeholder="Enter Sale Price" value="{{old('sell_price')}}" name="sell_price">
            </div>   
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Actual Price:</label>
                <input type="number" min="1" step="any" max="10000" class="form-control" required id="" placeholder="Enter Question" value="{{old('actual_price')}}" name="actual_price">
            </div>   
            
            <div class="row"><h5>Add Images</h5></div>   
                <div class="field_wrapper">
                    <div class="row">
                        <div class="mt-2">
                            <input type="file"  class="form-control" required name="image[]" accept="image/*"/>
                            <a href="javascript:void(0);"  class="add_button mt-2 btn btn-primary" title="Add field">Add more</a>
                        </div>
                    </div>
                </div>
            <div class="row mt-5"><h5>Add Varient</h5></div>
                <div class="field_wrapper2">
                    <div class="row">
                        <div class="mt-2">
                            <label for="email" class="form-label">Name:</label>
                            <input type="text" class="form-control" required name="varient[0][name]" value=""/>
                            <label for="email" class="form-label">Value:</label>
                            <input type="text" class="form-control"  required  name="varient[0][value]" value=""/>
                            <a href="javascript:void(0);" class="add_button2 btn btn-primary mt-2" title="Add field">Add more</a>
                        </div>
                    </div>
                </div>
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
</div>
@endsection
@section('extra-scripts')
<script type="text/javascript">
$(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var fieldHTML = '<div class="row"><div class="mt-2"><input type="file" class="form-control" accept="image/*" name="image[]"/><a href="javascript:void(0);" class="remove_button btn btn-warning">Remove</a></div></div>'; //New input field html 
    var x = 1; //Initial field counter is 1
    
    //Once add button is clicked
    $(addButton).click(function(){
        //Check maximum number of input fields
        if(x < maxField){ 
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); //Add field html
        }
    });
    
    //Once remove button is clicked
    $(wrapper).on('click', '.remove_button', function(e){
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
    });




    var maxField2 = 10; //Input fields increment limitation
    var addButton2 = $('.add_button2'); //Add button selector
    var wrapper2 = $('.field_wrapper2'); //Input field wrapper
    var x2 = 1; //Initial field counter is 1
    var fieldHTML2 = '<div class="row"><div class="mt-2"><label for="email" class="form-label">Name:</label><input type="text" class="form-control" name="varient['+x2+'][name]" value=""/><label for="email" class="form-label">Value:</label><input type="text" class="form-control" name="varient['+x2+'][value]" value=""/><a href="javascript:void(0);" class="remove_button2 mt-2 btn btn-warning" title="Add field">Remove</a></div></div>'; //New input field html 
    
    
    //Once add button is clicked
    $(addButton2).click(function(){
        //Check maximum number of input fields
        if(x2 < maxField2){ 
            x2++; //Increment field counter
            $(wrapper2).append(fieldHTML2); //Add field html
        }
    });
    
    //Once remove button is clicked
    $(wrapper2).on('click', '.remove_button2', function(e){
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x2--; //Decrement field counter
    });

});
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Edit Prodcut</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('products.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" enctype="multipart/form-data" action="{{route('products.update',$data->id)}}">
            @csrf
            @method('PUT')
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Name:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Name" value="{{old('name',$data->name)}}" name="name">
            </div>   
            @error('name')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Sale Price:</label>
                <input type="number" min="1" step="any" max="10000" class="form-control" required id="" placeholder="Enter Sale Price" value="{{old('sell_price',$data->sell_price)}}" name="sell_price">
            </div>   
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Actual Price:</label>
                <input type="number" min="1" step="any" max="10000" class="form-control" required id="" placeholder="Enter Question" value="{{old('actual_price',$data->actual_price)}}" name="actual_price">
            </div>   
            @foreach($data->images as $img)
                <div class="row">
                    <div class="mt-2">
                        <figure style="height:200px"><img  style="height:200px" src="{{$img->image_url}}" /></figure>
                        <a href="{{route('products.imageDelete',$img->id)}}"  class=" mt-2 btn btn-primary" title="">Delete</a>
                    </div>
                </div>
            @endforeach
            <div class="row"><h5>Add Images</h5></div>   
                <div class="field_wrapper">
                    <div class="row">
                        <div class="mt-2">
                            <input type="file"  class="form-control" name="image[]" accept="image/*"/>
                            <a href="javascript:void(0);"  class="add_button mt-2 btn btn-primary" title="Add field">Add more</a>
                        </div>
                    </div>
                </div>
            @foreach($data->varients as $key=>$var)
                <div class="row">
                    <div class="mt-2">
                        <input type="hidden" name="varient[{{$key}}][id]"  value="{{$var->id}}"/>
                        <label for="email" class="form-label">Name:</label>
                        <input type="text" class="form-control"  name="varient[{{$key}}][name]" value="{{$var->name}}"/>
                        <label for="email" class="form-label">Value:</label>
                        <input type="text" class="form-control"  name="varient[{{$key}}][value]" value="{{$var->value}}"/>
                        <a href="{{route('products.varientDelete',$var->id)}}"  class=" mt-2 btn btn-primary" title="">Delete</a>
                    </div>
                </div>
            @endforeach
            <div class="row mt-5"><h5>Add Varient</h5></div>
                <div class="field_wrapper2">
                    <div class="row">
                        <div class="mt-2">
                            <input type="hidden" name="varient[{{count($data->varients)}}][id]"  value="0"/>
                            <label for="email" class="form-label">Name:</label>
                            <input type="text" class="form-control"  name="varient[{{count($data->varients)}}][name]" value=""/>
                            <label for="email" class="form-label">Value:</label>
                            <input type="text" class="form-control"  name="varient[{{count($data->varients)}}][value]" value=""/>
                            <a href="javascript:void(0);" class="add_button2 btn btn-primary mt-2" title="Add field">Add more</a>
                        </div>
                    </div>
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection
@section('extra-scripts')
<script type="text/javascript">
$(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var fieldHTML = '<div class="row"><div class="mt-2"><input type="file" class="form-control" accept="image/*" name="image[]"/><a href="javascript:void(0);" class="remove_button btn btn-warning">Remove</a></div></div>'; //New input field html 
    var x = 1; //Initial field counter is 1
    
    //Once add button is clicked
    $(addButton).click(function(){
        //Check maximum number of input fields
        if(x < maxField){ 
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); //Add field html
        }
    });
    
    //Once remove button is clicked
    $(wrapper).on('click', '.remove_button', function(e){
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
    });




    var maxField2 = 10; //Input fields increment limitation
    var addButton2 = $('.add_button2'); //Add button selector
    var wrapper2 = $('.field_wrapper2'); //Input field wrapper
    var x2 = {{count($data->Varients)}}+1; //Initial field counter is 1
    var fieldHTML2 = '<div class="row"><div class="mt-2"><input type="hidden" name="varient['+x2+'][id]"  value="0"/><label for="email" class="form-label">Name:</label><input type="text" class="form-control" name="varient['+x2+'][name]" value=""/><label for="email" class="form-label">Value:</label><input type="text" class="form-control" name="varient['+x2+'][value]" value=""/><a href="javascript:void(0);" class="remove_button2 mt-2 btn btn-warning" title="Add field">Remove</a></div></div>'; //New input field html 
    
    
    //Once add button is clicked
    $(addButton2).click(function(){
        //Check maximum number of input fields
        if(x2 < maxField2){ 
            x2++; //Increment field counter
            $(wrapper2).append(fieldHTML2); //Add field html
        }
    });
    
    //Once remove button is clicked
    $(wrapper2).on('click', '.remove_button2', function(e){
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x2--; //Decrement field counter
    });

});
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Products</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('products.create')}}" class="btn btn-primary">Add Product</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-light table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Sale Price</th>
                <th>Actual Price</th>
                <th>Created at</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                @forelse($data as $val)
                <tr>
                    <td>{{$val->name}}</td>
                    <td>{{$val->sell_price}}</td>
                    <td>{{$val->actual_price}}</td>
                    <td>{{$val->created_at}}</td>
                    <td>
                        <a href="{{ route('products.edit', [base64_encode($val->id)]) }}"
                            class="btn btn-primary btn-sm">Edit</a>
                        <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-confirm"
                            data-form="deleteForm-{{ $val->id }}">Delete</a>
                        <form id="deleteForm-{{ $val->id }}"
                            action="{{ route('products.destroy', [base64_encode($val->id)]) }}" method="post">
                            @csrf @method('DELETE')
                        </form>
                    </td>  
                </tr>
                @empty
                <tr>
                    <td colspan="5">No Products</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="row">
        {!! $data->links() !!}
    </div>
</div>
@endsection