routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('products', 'ProductController');
        Route::get('imageDelete/{id}', 'ProductController@imageDelete')->name('products.imageDelete');
        Route::get('varientDelete/{id}', 'ProductController@varientDelete')->name('products.varientDelete');

    });
    
    Route::get('view-products', 'ProductController@index')->name('userProduct.index');
    Route::get('product-detail/{id}', 'ProductController@getProduct')->name('userProduct.detail');

});

resources/views/includes/navbar.blade.php
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <div class="container justify-content-center">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {{ request()->segment(1) == 'products' ?'active':''}}" href="{{route('products.index')}}">Manage Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('logout')}}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

resources/views/includes/userNav.blade.php
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top mb-5">
  <div class="container">
    <ul class="navbar-nav" style="display: contents">
        <li class="nav-item">
            <a class="nav-link {{ request()->segment(1) == 'view-products' ?'active':''}}" href="{{route('userProduct.index')}}">Products</a>
        </li>
    </ul>
  </div>
</nav>